site_name: 'Win It'
site_description: 'Win it docs'
site_author: 'Jarno Bogaert'
docs_dir: docs/
repo_name: 'jarnobogaert9/winit'
repo_url: 'https://github.com/jarnobogaert9/winit'

nav:
    - 'Home': './'
    - 'Modules': '/Modules/'

theme:
  name: 'material'